// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzmdcnkhgsfvoqilityb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6bWRjbmtoZ3Nmdm9xaWxpdHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDQ1NzAsImV4cCI6MjA2MzQyMDU3MH0.gL3AQcNxqk6CccjqiGiml3dNBdQxFK6WnyzVsXdmYwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);